### ISSUE TITLE
Resetting terminal cursor shape after exiting helix seems broken in 24.03

### ISSUE THREAD

**Issue by archseer** [helix-editor/helix#10089]
### Discussed in https://github.com/helix-editor/helix/discussions/10071

<div type='discussions-op-text'>

<sup>Originally posted by **wyw** March 31, 2024</sup>

https://github.com/helix-editor/helix/assets/11427457/011b634b-89bd-4caf-b3bf-7f8b14980406

### Related issue & PR:
- https://github.com/helix-editor/helix/issues/2684
- https://github.com/helix-editor/helix/pull/8591
- [commits/553ffbc](https://github.com/helix-editor/helix/commits/553ffbcaa09847ec606539bddab8af1456450d73/helix-tui/src/backend/crossterm.rs)

Resetting the terminal cursor shape after exiting helix worked before the commit 553ffbc in version a2767269:

https://github.com/helix-editor/helix/assets/11427457/1d25ddfc-f02e-4c95-86e6-f8f2e4b2a50e
</div>

**Comment by archseer** [comment]
Relevant comment from @kladd https://github.com/helix-editor/helix/pull/8591#issuecomment-1798215620 that I've originally missed since it was made after the PR was already merged

**Comment by pascalkuthe** [comment]
We should probably check what vim does and copy that. Terminfo is just a garden of weirdly noncompatible stuff (as is everything with terminals in general)

**Comment by lpoirothattermann** [comment]
Same behavior for me.

**Comment by kirawi** [comment]
Are we planning to backport this to 24.03? It seems like it could be a significant regression.

**Comment by kirawi** [comment]
Detection seems to be handled by the second variable on https://github.com/neovim/neovim/blob/30b94ae4942b4e82030bc079368dd7fcb5481456/src/nvim/tui/tui.c#L133

They have a dedicated function for terminfo: https://github.com/neovim/neovim/blob/30b94ae4942b4e82030bc079368dd7fcb5481456/src/nvim/tui/tui.c#L1882

https://github.com/neovim/neovim/blob/30b94ae4942b4e82030bc079368dd7fcb5481456/src/nvim/tui/tui.c#L2106-L2110
https://github.com/neovim/neovim/blob/30b94ae4942b4e82030bc079368dd7fcb5481456/src/nvim/tui/tui.c#L2143-L2173
https://github.com/neovim/neovim/blob/30b94ae4942b4e82030bc079368dd7fcb5481456/src/nvim/tui/tui.c#L2189-L2195

**Comment by kirawi** [comment]
I think we'd want to add it to this function: https://github.com/helix-editor/helix/blob/97afd67fca0b505600e5fbba7ca59f06a4eec3ff/helix-tui/src/backend/crossterm.rs#L57-L78

**Comment by cjbayliss** [comment]
temporary workaround for `fish` users using `alacritty`, shouldn't be to hard to adapt for other shells:

```fish
# FIXME: remove once https://github.com/helix-editor/helix/issues/10089 is fixed
function hx
    command hx $argv
    printf '\033[0 q'
end
```

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/issues/6565 is related

**Comment by mobsenpai** [comment]
Having the same problem since updating to nixos 24.05.

**Comment by pascalkuthe** [comment]
fixed by #10769

**Comment by wyw** [comment]
Still not working properly in iTerm2 (and Apple Terminal) after the fix.

https://github.com/helix-editor/helix/assets/11427457/9c6d261b-328c-42e6-9e75-2c3723103cdd

**Comment by chrispyles** [comment]
I am also still experiencing this issue on iTerm2.

**Comment by kirawi** [comment]
Reopening to track why it hasn't been fixed

**Comment by staticf0x** [comment]
Still happening in `helix 25.01.1 (e7ac2fcd)` in `fish` in Ptyxis terminal on Fedora 41.

**Comment by pascalkuthe** [comment]
there just isn't a good general pupose solution to this one. We tried quite hard to take terminfo into account and have reasonable fallbacks at the same time but at then end of the day the escape sequence is not standardized across terminals (and terminfo is brittle)so there is not standard way to fix this. nvim doesn't even attempt to do this at all and makes the user configure an escape sequence to reset the cursor themselves.

**Comment by staticf0x** [comment]
Would it be possible to add this to helix as well? A configurable escape sequence on exit? It probably feels hacky as well, but would come handy when using helix as `$EDITOR` in git commit messages where the fish function wrapper doesn't apply.

**Comment by stag-enterprises** [comment]
rather than detecting the user's default cursor or trying to reset to it, what about having the user manually specify what cursor they want to default to?

**Comment by thetredev** [comment]
I agree with @stag-enterprises. Seems to be the easiest option from an end user's perspective.
