### ISSUE TITLE
error installing on m1

### ISSUE THREAD

**Issue by GopherJ** [helix-editor/helix#109]
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/33961674/120762423-d3671f00-c548-11eb-9b35-2c2f256ee516.png">

**Comment by archseer** [comment]
It looks like it's failing to find a numeric OPT_LEVEL https://github.com/helix-editor/helix/blob/4f0e3aa948a83c0d94f942448bfa7740532e55b7/helix-syntax/build.rs#L7 can you do some testing to see what exactly it's set to?

**Comment by archseer** [comment]
Ah okay, looks like those calls aren't required:

> This option is automatically scraped from the OPT_LEVEL environment variable by build scripts, so it’s not required to call this function.

**Comment by archseer** [comment]
Can you remove these lines and try again?

https://github.com/helix-editor/helix/blob/4f0e3aa948a83c0d94f942448bfa7740532e55b7/helix-syntax/build.rs#L61-L62

https://github.com/helix-editor/helix/blob/4f0e3aa948a83c0d94f942448bfa7740532e55b7/helix-syntax/build.rs#L76-L77

**Comment by archseer** [comment]
Hopefully fixed by 8f78c0c61291d81180ca0549b4df1fada6a13498

**Comment by GopherJ** [comment]
@archseer actually I still have this issue after rebase master

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/33961674/120874835-11ad1e80-c5db-11eb-8622-aeee428a9dbf.png">

**Comment by archseer** [comment]
Can you provide the whole log output? I'd like to see what the OPT_LEVEL is set to.

**Comment by GopherJ** [comment]
```
     Running `rustc --crate-name tree_sitter --edition=2018 /Users/alex_cj96/.cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-0.19.5/binding_rust/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=z -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C metadata=599b65fdb043da14 -C extra-filename=-599b65fdb043da14 --out-dir /Users/alex_cj96/Downloads/helix/target/release/deps -L dependency=/Users/alex_cj96/Downloads/helix/target/release/deps --extern regex=/Users/alex_cj96/Downloads/helix/target/release/deps/libregex-6d9fea4269ff6882.rmeta --cap-lints allow -L native=/Users/alex_cj96/Downloads/helix/target/release/build/tree-sitter-9653b0fde607ff91/out -l static=tree-sitter`
error: failed to run custom build command for `helix-syntax v0.1.0 (/Users/alex_cj96/Downloads/helix/helix-syntax)`

Caused by:
  process didn't exit successfully: `/Users/alex_cj96/Downloads/helix/target/release/build/helix-syntax-70503d9fdc69eb4c/build-script-build` (exit code: 101)
  --- stdout
  Build language go
  Build language bash
  Build language elixir
  Build language python
  Build language html
  Build language java
  Build language rust
  Build language cpp
  Build language toml
  Build language c
  Build language php
  Build language ruby
  Build language swift
  Build language scala
  Build language javascript
  Build language agda
  Build language css
  Build language json
  Build language c-sharp
  Build language julia

  --- stderr
  Collect files for tree-sitter-go
  Collect files for tree-sitter-bash
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  Collect files for tree-sitter-elixir
  stack backtrace:
  Collect files for tree-sitter-python
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }thread '', helix-syntax/build.rs:7:51
  <unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  Collect files for ', tree-sitter-htmlhelix-syntax/build.rs
  :7:51
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  Collect files for tree-sitter-java
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  Collect files for tree-sitter-cpp
  Collect files for tree-sitter-rust
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{Collect files for tree-sitter-toml
  closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     Collect files for 3tree-sitter-c:
  core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }call_box
  ', helix-syntax/build.rs:7 : 51
  9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
   Collect files for  tree-sitter-php 0: rust_begin_unwind

               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  thread '<unnamed> ' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
    2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at Collect files for /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rstree-sitter-ruby:
  1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', call_boxhelix-syntax/build.rs
  :7  :51
   9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
  Collect files for  tree-sitter-swift
   3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpoolthread '::<unnamed>FnBox' panicked at '>called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  ::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
  Collect files for  tree-sitter-scala
   5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>Collect files for tree-sitter-javascript
  ::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: coreCollect files for ::tree-sitter-agdapanicking::panic_fmt

               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}thread '<unnamed>' panicked at '
  called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7 : 51 8: <F as threadpool::
  FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5Collect files for tree-sitter-css
  : build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::thread 'call_box<unnamed>
  ' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs: 7 : 519
  : threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
   Collect files for  tree-sitter-json
  5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:stack backtrace:
  7:51
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
  Collect files for tree-sitter-c-sharp
    6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', helix-syntax/build.rs:7:51
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::ResultCollect files for tree-sitter-julia
  <T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }   9: threadpool::spawn_in_pool::{{closure', }}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  helix-syntax/build.rs:7:51
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::option::expect_none_failed
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::get_opt_level
     5: build_script_build::build_c
     6: build_script_build::build_dir
     7: build_script_build::main::{{closure}}
     8: <F as threadpool::FnBox>::call_box
     9: threadpool::spawn_in_pool::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `0`,
   right: `20`', helix-syntax/build.rs:134:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
     2: core::panicking::assert_failed::inner
     3: core::panicking::assert_failed
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `helix-term v0.1.0 (/Users/alex_cj96/Downloads/helix/helix-term)`, intermediate artifacts can be found at `/Users/alex_cj96/Downloads/helix/target`

Caused by:
  build failed
```

**Comment by archseer** [comment]
Are you sure you're on the latest master? `build_script_build::get_opt_level` is getting called, but that function doesn't exist after https://github.com/helix-editor/helix/commit/8f78c0c61291d81180ca0549b4df1fada6a13498

**Comment by GopherJ** [comment]
@archseer yes not sure why git rebase failed, now I pulled latest changes and I'll let you know, thanks

**Comment by archseer** [comment]
This happened on the CI: https://github.com/helix-editor/helix/runs/2759679797

**Comment by atog** [comment]
Not sure if this helps, but I'm running Helix from master on a macOS with M1. 

Let me know if I need to test something specific.

**Comment by sangshuduo** [comment]
i'm not luck to build master on my M1max MBP with rust 1.59.

$ rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)

...
warning: function is never used: `env_var_is_set`
   --> helix-view/src/clipboard.rs:123:4
    |
123 | fn env_var_is_set(env_var_name: &str) -> bool {
    |    ^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: function is never used: `is_exit_success`
   --> helix-view/src/clipboard.rs:127:4
    |
127 | fn is_exit_success(program: &str, args: &[&str]) -> bool {
    |    ^^^^^^^^^^^^^^^

   Compiling helix-tui v0.6.0 (/Users/sangshuduo/work/rust/helix/helix-tui)
warning: `helix-view` (lib) generated 2 warnings
error: failed to compile `helix-term v0.6.0 (/Users/sangshuduo/work/rust/helix/helix-term)`, intermediate artifacts can be found at `/Users/sangshuduo/work/rust/helix/target`

Caused by:
  failed to run custom build command for `helix-term v0.6.0 (/Users/sangshuduo/work/rust/helix/helix-term)`

Caused by:
  process didn't exit successfully: `/Users/sangshuduo/work/rust/helix/target/release/build/helix-term-641e66af85a9a639/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Failed to fetch tree-sitter grammars: Failed to fetch some grammar(s)

  Caused by:
      Git command failed.
      Stdout:
      Stderr: kex_exchange_identification: Connection closed by remote host
      Connection closed by 20.205.243.166 port 22
      fatal: Could not read from remote repository.

      Please make sure you have the correct access rights
      and the repository exists.
      ', helix-term/build.rs:19:26
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by archseer** [comment]
You have some sort of connection issue that's preventing you from fetching tree-sitter grammars.

**Comment by sangshuduo** [comment]
> You have some sort of connection issue that's preventing you from fetching tree-sitter grammars.

thanks for point out
