### ISSUE TITLE
Text edits with the same start position are applied in reverse

### ISSUE THREAD

**Issue by kyoh86** [helix-editor/helix#11174]
### Summary

Text edits returned from the LSP that have the same start position are being applied in reverse.
According to the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEditArray), text edits with the same start position should be applied in the order received.

Recently, the language server client included with Neovim has fixed this bug (https://github.com/neovim/neovim/issues/29202)

Accordingly, using some servers (e.g. [efm-langserver](https://github.com/mattn/efm-langserver)) with the client included with Neovim, the formatted lines of the result may be reversed.
So I tried to ask the server to fix it (https://github.com/mattn/efm-langserver/issues/281), but the fix causes problems with other (non-specified) clients such as Helix.
Therefore, I would like you to implement a fix in Helix that follows the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEditArray), as well as Neovim.

### Reproduction Steps

1. Install efm-langserver with patch to follow the LSP spec.

```console
$ git clone --branch fix-281 https://github.com/kyoh86/efm-langserver.git
$ cd efm-langserver
$ go install .
```

2. Set the path

```console
$ export PATH="$(go env GOPATH)/bin:$PATH"
```

3. Configure the Helix

helix/languages.toml

```
[language-server.efm]
command = "efm-langserver"

[[language]]
name = "go"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] },
]
```

4. Configure the efm-langserver

```
version: 2

tools:
  echo-fix: &echo-fix
    format-command: zsh -c 'print "foo\nbar\nbaz"'
    format-stdin: true

languages:
  json:
    - <<: *echo-fix
```

5. Open helix

```console
$ hx foo.json
```

6. Call `:format`

Expected result: 

```
foo
bar
baz
```

But actual result:

```
baz
bar
foo
```

If you install the efm-langserver without the patch, this doesn't happen.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-07-15T14:46:45.102 helix_lsp::transport [ERROR] efm err <- "2024/07/15 14:46:45 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n"
2024-07-15T14:46:45.104 helix_lsp::transport [ERROR] efm err <- "2024/07/15 14:46:45 efm-langserver: connections closed\n"
2024-07-15T14:46:45.102 helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream
2024-07-15T14:46:45.104 helix_lsp::transport [ERROR] efm err: <- StreamClosed
2024-07-15T14:46:45.104 helix_lsp::transport [ERROR] efm err: <- IO(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
```

</details>

### Platform

Linux

### Terminal Emulator

WezTerm

### Installation Method

releases page

### Helix Version

helix 24.7 (079f5442)

**Comment by pascalkuthe** [comment]
does this match what vscode does? You will have a hard time convincing servers to follow the spec if vscode doesn't follow it unfortunately so that is the the behaviour I would aim to emulate

**Comment by kyoh86** [comment]
@pascalkuthe Thank you for your reply.

In the Neovim issue that triggered this modification, it is stated that it follows the VSCode implementation as follows.
Therefore, it is assumed that VSCode also processes in the same order.

> Also, in the [vscode implementation](https://github.com/microsoft/vscode-languageserver-node/blob/main/textDocument/src/main.ts#L371), similar start position text edits aren't sorted in reverse order

I do not know how to apply formatting using VSCode and a language server, and have not been able to confirm how "changes across multiple consecutive lines" like efm-langserver are handled.

**Comment by kyoh86** [comment]
It has fixed in Neovim, thanks.

**Comment by pascalkuthe** [comment]
This still appear in helix because we accidentally perform an unstable sort (instead of a stable sort).

Just need to replace this [here](https://github.com/helix-editor/helix/blob/30fb63cc3df96a0c79820dd2980a570cce11c8c3/helix-lsp/src/lib.rs#L506)
