### ISSUE TITLE
Stop changing the cursor

### ISSUE THREAD

**Issue by djmattyg007** [helix-editor/helix#11883]
### Summary

I use Windows Terminal and WSL. I have my terminal configured to use the "bar" cursor. By default, Helix wants to use the "block" cursor. Even when I configure it to use a "bar" cursor, it still resets the cursor to "block" when Helix exits.

### Reproduction Steps

I added this to my config file:

```toml
[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "bar"
```

When Helix opens, it "maintains" the current cursor, which is meant to be "bar".

Now close Helix, without performing any other actions. It changes the cursor to "block" anyway, despite being configured to not use "block".

### Helix log

I deleted the log file before performing the reproduction steps. Upon completing the reproduction steps, the log file was present but empty. There's nothing to provide here.

### Platform

Linux inside WSL

### Terminal Emulator

Windows Terminal 1.21.2361.0

### Installation Method

Arch Linux official repos

### Helix Version

helix 24.7

**Comment by djmattyg007** [comment]
From my perspective, the ideal solution would be to provide an option that prevents Helix from altering the terminal cursor at all. I don't want to customise the appearance of the cursor, and I don't want my software changing the appearance of the cursor. I want the cursor I've configured myself in my terminal to be the only cursor that is used.

**Comment by djmattyg007** [comment]
I know I'm far from the first person to discuss the issue of cursor management in this project. I submitted this report for two reasons:

1. I hadn't seen anyone else report the issue of Helix resetting to "block" cursor on exit no matter what is configured.
2. I hadn't seen anyone else request support for "please do not alter my cursor at all".

**Comment by kujohn** [comment]
I also have an issue with cursor changing from underline to block upon entering and existing helix

**Comment by jeancf** [comment]
I have been experiencing this issue for months as well on linux with Konsole and Alacritty. I though this was a regression that would go away at the next release and did not bother coming here. But since it did not get fixed in 25.01 I came to chime in.

**Comment by EpicVon2468** [comment]
Experiencing this as well on Konsole (helix 25.07.1 via nixpkgs)

**Comment by jahinzee** [comment]
I'm also still having this issue on Konsole and Yakuake (helix 25.07.1, installed from nixpkgs)

**Comment by EpicVon2468** [comment]
It's fixed for me on git latest but obviously that's not exactly ideal for most users
