### ISSUE TITLE
Panic/crash on f157a918

### ISSUE THREAD

**Issue by altwazar** [helix-editor/helix#13569]
### Summary

Crash on auto-completion `use std::pin` or "show docs for item under cursor" on `pin` in this line.

### Reproduction Steps

 

I tried this:

1. `cargo new hxtest && cd hxtest && hx src/main.rs`

2. Type `use std::pin` then tab

Get crash:

```
thread 'main' panicked at helix-term/src/ui/markdown.rs:93:9:
assertion failed: pos > start
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: helix_term::ui::markdown::highlighted_code_block
   4: helix_term::ui::markdown::Markdown::parse
   5: <helix_term::ui::markdown::Markdown as helix_term::compositor::Component>::render
   6: <helix_term::ui::completion::Completion as helix_term::compositor::Component>::render
   7: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::render
   8: helix_term::application::Application::render::{{closure}}
   9: hx::main_impl::{{closure}}
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::context::runtime::enter_runtime
  12: tokio::runtime::runtime::Runtime::block_on
  13: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
[helix.log](https://github.com/user-attachments/files/20277942/helix.log)
</details>

### Platform

Linux

### Terminal Emulator

wezterm 20240203-110809-5046fc22-gentoo

### Installation Method

source

### Helix Version

helix 25.01.1 (f157a918)

**Comment by CalebLarsen** [comment]
I was able to reproduce and found another way to trigger that I think is worth noting.
```rust
/// ```
/// /// `Something`
/// /// Anything
/// ```
struct Broken {}
```

This crashes when hovering `Broken`. Something about the highlighting for ``Something`` makes the `syntax_highlighter` get hung up and not advance the position to highlight.

**Comment by the-mikedavis** [comment]
Fixed in 7410fe35a3baf47b9d2514f60b440621d0fc8a10. Also see the fix in tree-house https://github.com/helix-editor/tree-house/commit/c9fa54f2eb71918e2912d683e69422a2ed3a02dc

**Comment by SymphonySimper** [comment]
This still happens with `tailwindcss-ls`. When you hover over the class name `prose` (provided by [@tailwindcss/typography](https://github.com/tailwindlabs/tailwindcss-typography/tree/main)).

## Steps to reproduce

Any `tailwindcss` project with `@tailwindcss/typography` plugin installed.

```html
<div class="prose"></div>
```

When you use `<space>k` over `prose` helix panics.


## Response from LSP

```
2025-06-07T17:02:58.274 helix_lsp::transport [INFO] tailwindcss-ls <- {"jsonrpc":"2.0","id":11,"result":{"contents":{"language":"css","value":".prose {\n  color: var(--tw-prose-body);\n  max-width: 65ch;\n  :where(p):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 1.25em;\n    margin-bottom: 1.25em;\n  }\n  :where([class~=\"lead\"]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-lead);\n    font-size: 1.25em;\n    line-height: 1.6;\n    margin-top: 1.2em;\n    margin-bottom: 1.2em;\n  }\n  :where(a):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-links);\n    text-decoration: underline;\n    font-weight: 500;\n  }\n  :where(strong):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-bold);\n    font-weight: 600;\n  }\n  :where(a strong):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n  }\n  :where(blockquote strong):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n  }\n  :where(thead th strong):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n  }\n  :where(ol):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: decimal;\n    margin-top: 1.25em;\n    margin-bottom: 1.25em;\n    padding-inline-start: 1.625em;\n  }\n  :where(ol[type=\"A\"]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: upper-alpha;\n  }\n  :where(ol[type=\"a\"]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: lower-alpha;\n  }\n  :where(ol[type=\"A\" s]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: upper-alpha;\n  }\n  :where(ol[type=\"a\" s]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: lower-alpha;\n  }\n  :where(ol[type=\"I\"]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: upper-roman;\n  }\n  :where(ol[type=\"i\"]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: lower-roman;\n  }\n  :where(ol[type=\"I\" s]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: upper-roman;\n  }\n  :where(ol[type=\"i\" s]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: lower-roman;\n  }\n  :where(ol[type=\"1\"]):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: decimal;\n  }\n  :where(ul):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    list-style-type: disc;\n    margin-top: 1.25em;\n    margin-bottom: 1.25em;\n    padding-inline-start: 1.625em;\n  }\n  :where(ol > li):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *))::marker {\n    font-weight: 400;\n    color: var(--tw-prose-counters);\n  }\n  :where(ul > li):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *))::marker {\n    color: var(--tw-prose-bullets);\n  }\n  :where(dt):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-headings);\n    font-weight: 600;\n    margin-top: 1.25em;\n  }\n  :where(hr):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    border-color: var(--tw-prose-hr);\n    border-top-width: 1;\n    margin-top: 3em;\n    margin-bottom: 3em;\n  }\n  :where(blockquote):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    font-weight: 500;\n    font-style: italic;\n    color: var(--tw-prose-quotes);\n    border-inline-start-width: 0.25rem /* 4px */;\n    border-inline-start-color: var(--tw-prose-quote-borders);\n    quotes: \"\\201C\"\"\\201D\"\"\\2018\"\"\\2019\";\n    margin-top: 1.6em;\n    margin-bottom: 1.6em;\n    padding-inline-start: 1em;\n  }\n  :where(blockquote p:first-of-type):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *))::before {\n    content: open-quote;\n  }\n  :where(blockquote p:last-of-type):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *))::after {\n    content: close-quote;\n  }\n  :where(h1):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-headings);\n    font-weight: 800;\n    font-size: 2.25em;\n    margin-top: 0;\n    margin-bottom: 0.8888889em;\n    line-height: 1.1111111;\n  }\n  :where(h1 strong):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    font-weight: 900;\n    color: inherit;\n  }\n  :where(h2):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-headings);\n    font-weight: 700;\n    font-size: 1.5em;\n    margin-top: 2em;\n    margin-bottom: 1em;\n    line-height: 1.3333333;\n  }\n  :where(h2 strong):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    font-weight: 800;\n    color: inherit;\n  }\n  :where(h3):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-headings);\n    font-weight: 600;\n    font-size: 1.25em;\n    margin-top: 1.6em;\n    margin-bottom: 0.6em;\n    line-height: 1.6;\n  }\n  :where(h3 strong):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    font-weight: 700;\n    color: inherit;\n  }\n  :where(h4):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-headings);\n    font-weight: 600;\n    margin-top: 1.5em;\n    margin-bottom: 0.5em;\n    line-height: 1.5;\n  }\n  :where(h4 strong):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    font-weight: 700;\n    color: inherit;\n  }\n  :where(img):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 2em;\n    margin-bottom: 2em;\n  }\n  :where(picture):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    display: block;\n    margin-top: 2em;\n    margin-bottom: 2em;\n  }\n  :where(video):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 2em;\n    margin-bottom: 2em;\n  }\n  :where(kbd):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    font-weight: 500;\n    font-family: inherit;\n    color: var(--tw-prose-kbd);\n    box-shadow: 0 0 0 1px rgb(var(--tw-prose-kbd-shadows) / 10%), 0 3px 0 rgb(var(--tw-prose-kbd-shadows) / 10%);\n    font-size: 0.875em;\n    border-radius: 0.3125rem /* 5px */;\n    padding-top: 0.1875em;\n    padding-inline-end: 0.375em;\n    padding-bottom: 0.1875em;\n    padding-inline-start: 0.375em;\n  }\n  :where(code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-code);\n    font-weight: 600;\n    font-size: 0.875em;\n  }\n  :where(code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *))::before {\n    content: \"`\";\n  }\n  :where(code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *))::after {\n    content: \"`\";\n  }\n  :where(a code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n  }\n  :where(h1 code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n  }\n  :where(h2 code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n    font-size: 0.875em;\n  }\n  :where(h3 code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n    font-size: 0.9em;\n  }\n  :where(h4 code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n  }\n  :where(blockquote code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n  }\n  :where(thead th code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: inherit;\n  }\n  :where(pre):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-pre-code);\n    background-color: var(--tw-prose-pre-bg);\n    overflow-x: auto;\n    font-weight: 400;\n    font-size: 0.875em;\n    line-height: 1.7142857;\n    margin-top: 1.7142857em;\n    margin-bottom: 1.7142857em;\n    border-radius: 0.375rem /* 6px */;\n    padding-top: 0.8571429em;\n    padding-inline-end: 1.1428571em;\n    padding-bottom: 0.8571429em;\n    padding-inline-start: 1.1428571em;\n  }\n  :where(pre code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    background-color: transparent;\n    border-width: 0;\n    border-radius: 0;\n    padding: 0;\n    font-weight: inherit;\n    color: inherit;\n    font-size: inherit;\n    font-family: inherit;\n    line-height: inherit;\n  }\n  :where(pre code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *))::before {\n    content: none;\n  }\n  :where(pre code):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *))::after {\n    content: none;\n  }\n  :where(table):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    width: 100%;\n    table-layout: auto;\n    margin-top: 2em;\n    margin-bottom: 2em;\n    font-size: 0.875em;\n    line-height: 1.7142857;\n  }\n  :where(thead):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    border-bottom-width: 1px;\n    border-bottom-color: var(--tw-prose-th-borders);\n  }\n  :where(thead th):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-headings);\n    font-weight: 600;\n    vertical-align: bottom;\n    padding-inline-end: 0.5714286em;\n    padding-bottom: 0.5714286em;\n    padding-inline-start: 0.5714286em;\n  }\n  :where(tbody tr):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    border-bottom-width: 1px;\n    border-bottom-color: var(--tw-prose-td-borders);\n  }\n  :where(tbody tr:last-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    border-bottom-width: 0;\n  }\n  :where(tbody td):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    vertical-align: baseline;\n  }\n  :where(tfoot):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    border-top-width: 1px;\n    border-top-color: var(--tw-prose-th-borders);\n  }\n  :where(tfoot td):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    vertical-align: top;\n  }\n  :where(th, td):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    text-align: start;\n  }\n  :where(figure > *):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0;\n    margin-bottom: 0;\n  }\n  :where(figcaption):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    color: var(--tw-prose-captions);\n    font-size: 0.875em;\n    line-height: 1.4285714;\n    margin-top: 0.8571429em;\n  }\n  --tw-prose-body: oklch(37.3% 0.034 259.733) /* #364153 */;\n  --tw-prose-headings: oklch(21% 0.034 264.665) /* #101828 */;\n  --tw-prose-lead: oklch(44.6% 0.03 256.802) /* #4a5565 */;\n  --tw-prose-links: oklch(21% 0.034 264.665) /* #101828 */;\n  --tw-prose-bold: oklch(21% 0.034 264.665) /* #101828 */;\n  --tw-prose-counters: oklch(55.1% 0.027 264.364) /* #6a7282 */;\n  --tw-prose-bullets: oklch(87.2% 0.01 258.338) /* #d1d5dc */;\n  --tw-prose-hr: oklch(92.8% 0.006 264.531) /* #e5e7eb */;\n  --tw-prose-quotes: oklch(21% 0.034 264.665) /* #101828 */;\n  --tw-prose-quote-borders: oklch(92.8% 0.006 264.531) /* #e5e7eb */;\n  --tw-prose-captions: oklch(55.1% 0.027 264.364) /* #6a7282 */;\n  --tw-prose-kbd: oklch(21% 0.034 264.665) /* #101828 */;\n  --tw-prose-kbd-shadows: NaN NaN NaN;\n  --tw-prose-code: oklch(21% 0.034 264.665) /* #101828 */;\n  --tw-prose-pre-code: oklch(92.8% 0.006 264.531) /* #e5e7eb */;\n  --tw-prose-pre-bg: oklch(27.8% 0.033 256.848) /* #1e2939 */;\n  --tw-prose-th-borders: oklch(87.2% 0.01 258.338) /* #d1d5dc */;\n  --tw-prose-td-borders: oklch(92.8% 0.006 264.531) /* #e5e7eb */;\n  --tw-prose-invert-body: oklch(87.2% 0.01 258.338) /* #d1d5dc */;\n  --tw-prose-invert-headings: #fff;\n  --tw-prose-invert-lead: oklch(70.7% 0.022 261.325) /* #99a1af */;\n  --tw-prose-invert-links: #fff;\n  --tw-prose-invert-bold: #fff;\n  --tw-prose-invert-counters: oklch(70.7% 0.022 261.325) /* #99a1af */;\n  --tw-prose-invert-bullets: oklch(44.6% 0.03 256.802) /* #4a5565 */;\n  --tw-prose-invert-hr: oklch(37.3% 0.034 259.733) /* #364153 */;\n  --tw-prose-invert-quotes: oklch(96.7% 0.003 264.542) /* #f3f4f6 */;\n  --tw-prose-invert-quote-borders: oklch(37.3% 0.034 259.733) /* #364153 */;\n  --tw-prose-invert-captions: oklch(70.7% 0.022 261.325) /* #99a1af */;\n  --tw-prose-invert-kbd: #fff;\n  --tw-prose-invert-kbd-shadows: 255 255 255;\n  --tw-prose-invert-code: #fff;\n  --tw-prose-invert-pre-code: oklch(87.2% 0.01 258.338) /* #d1d5dc */;\n  --tw-prose-invert-pre-bg: rgb(0 0 0 / 50%);\n  --tw-prose-invert-th-borders: oklch(44.6% 0.03 256.802) /* #4a5565 */;\n  --tw-prose-invert-td-borders: oklch(37.3% 0.034 259.733) /* #364153 */;\n  font-size: 1rem /* 16px */;\n  line-height: 1.75;\n  :where(picture > img):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0;\n    margin-bottom: 0;\n  }\n  :where(li):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0.5em;\n    margin-bottom: 0.5em;\n  }\n  :where(ol > li):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    padding-inline-start: 0.375em;\n  }\n  :where(ul > li):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    padding-inline-start: 0.375em;\n  }\n  :where(.prose > ul > li p):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0.75em;\n    margin-bottom: 0.75em;\n  }\n  :where(.prose > ul > li > p:first-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 1.25em;\n  }\n  :where(.prose > ul > li > p:last-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-bottom: 1.25em;\n  }\n  :where(.prose > ol > li > p:first-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 1.25em;\n  }\n  :where(.prose > ol > li > p:last-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-bottom: 1.25em;\n  }\n  :where(ul ul, ul ol, ol ul, ol ol):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0.75em;\n    margin-bottom: 0.75em;\n  }\n  :where(dl):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 1.25em;\n    margin-bottom: 1.25em;\n  }\n  :where(dd):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0.5em;\n    padding-inline-start: 1.625em;\n  }\n  :where(hr + *):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0;\n  }\n  :where(h2 + *):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0;\n  }\n  :where(h3 + *):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0;\n  }\n  :where(h4 + *):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0;\n  }\n  :where(thead th:first-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    padding-inline-start: 0;\n  }\n  :where(thead th:last-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    padding-inline-end: 0;\n  }\n  :where(tbody td, tfoot td):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    padding-top: 0.5714286em;\n    padding-inline-end: 0.5714286em;\n    padding-bottom: 0.5714286em;\n    padding-inline-start: 0.5714286em;\n  }\n  :where(tbody td:first-child, tfoot td:first-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    padding-inline-start: 0;\n  }\n  :where(tbody td:last-child, tfoot td:last-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    padding-inline-end: 0;\n  }\n  :where(figure):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 2em;\n    margin-bottom: 2em;\n  }\n  :where(.prose > :first-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-top: 0;\n  }\n  :where(.prose > :last-child):not(:where([class~=\"not-prose\"],[class~=\"not-prose\"] *)) {\n    margin-bottom: 0;\n  }\n}"},"range":{"start":{"line":3,"character":12},"end":{"line":3,"character":17}}}}
```

## RUST_BACKTRACE=1

```
thread 'main' panicked at helix-term/src/ui/markdown.rs:93:9:
assertion failed: pos > start
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: helix_term::ui::markdown::highlighted_code_block
   4: helix_term::ui::markdown::Markdown::parse
   5: <helix_term::ui::lsp::hover::Hover as helix_term::compositor::Component>::render
   6: <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::render
   7: helix_term::application::Application::render::{{closure}}
   8: hx::main_impl::{{closure}}
   9: tokio::runtime::park::CachedParkThread::block_on
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::runtime::Runtime::block_on
  12: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Helix version

```> hx --version
helix 25.01.1 (f4b488e3)
```

**Comment by the-mikedavis** [comment]
This is a separate broken invariant. I have a fix locally in tree-house but I will add more debug assertions with it so it is more obvious when we are breaking assumptions.

The most minimal reproduction I could find for this was:

```css
--color: #fff;
```

**Comment by the-mikedavis** [comment]
That should be fixed now in https://github.com/helix-editor/helix/commit/362e97e9275e3972b24d4a4b8a7287a338691370

**Comment by SymphonySimper** [comment]
> That should be fixed now in [362e97e](https://github.com/helix-editor/helix/commit/362e97e9275e3972b24d4a4b8a7287a338691370)

It works. Thanks a ton!
