### ISSUE TITLE
Package for Ubuntu

### ISSUE THREAD

**Issue by kirillmorozov** [helix-editor/helix#3640]
I've tried to find a repo with a .deb package for Ubuntu but failed.

Is there a community-maintained repo for Ubuntu?

If the answer is no, then I'd like to help even though I don't have an experience of creating/maintaining a PPA repo(but I was able to compile Helix from sources for my Linux Mint).

**Comment by the-mikedavis** [comment]
Afaik there is not currently a PPA or anything in apt. If you'd like to create and maintain a PPA, that would be great!

**Comment by uwearzt** [comment]
How should it be packaged? Is https://crates.io/crates/cargo-deb a good option? If yes, i would give it a try :)

**Comment by kirillmorozov** [comment]
@uwearzt, creating a Debian package via cargo-deb is easy, I did it on my local machine and it worked fine. The harder thing is packaging it in Ubuntu PPA according to all their rules. I've stuck on this step and never had a time to finish this.

Good thing is Pop!_OS team is hosting Alacritty Ubuntu packages on [PPA](https://launchpad.net/~mmstick76/+archive/ubuntu/alacritty) so it's possible to download their packaging code and adjust it to suite our needs.

And since maintainers of helix don't want to have any packaging code in this repo it should also be fairly simple to setup a repo with a GitHub action that'll pull the latest release from helix, add packaging code and upload it to PPA.

That was my plan but I'm going through serious life changing events at the moment so sorry that haven't done it yet.

**Comment by uwearzt** [comment]
@kirillmorozov Yes, cargo-deb was easy :). I will look into the ppa in the next weeks. Thanks for your help.

**Comment by uwearzt** [comment]
I tested creating a ppa, but i would prefer a package repo on github pages. 

Main points:

1. We could also provide packages for non Ubuntu (in my case Raspbian)
2. The build infrastructure on github is much faster
3. Everyone could provide patches via pull requests

The actual alacritty builds are also non ppa now: https://github.com/barnumbirr/alacritty-debian

If that's OK for you, assign me the issue, i will create the package repo in the next two weeks.

**Comment by uwearzt** [comment]
@baarkerlounger Yes, that is normally done in the postinst/postrm script. If you would like to have it after a cargo install you can do (set the correct path according to your directory):

```
sudo update-alternatives --install /usr/bin/editor editor /[mypath]/hx 100
```

see https://wiki.debian.org/DebianAlternatives

**Comment by maveonair** [comment]
> The actual alacritty builds are also non ppa now: https://github.com/barnumbirr/alacritty-debian

I used this repository as a reference to build my own deb package for Helix: https://github.com/maveonair/helix-debian

**Comment by baarkerlounger** [comment]
@maveonair will you be looking to get that submitted to debian repos?

**Comment by maveonair** [comment]
> @maveonair will you be looking to get that submitted to debian repos?

I am using PopOS and was rather considering to setup a PPA for it since PopOS is based on Ubuntu.

If someone wants to step in and help me to do it properly for Debian then I would be interested to make it happen.

**Comment by baarkerlounger** [comment]
@archseer looks like you have a placeholder on crates.io for this https://crates.io/crates/helix-editor. I gather uploading to Debian repos is a lot easier if a crate is published - would you be willing to do so?

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/issues/42, publishing Helix to crates.io is not planned

**Comment by maveonair** [comment]
I created my own PPA for Helix: https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor

**Comment by the-mikedavis** [comment]
Awesome, thank you!

**Comment by kirillmorozov** [comment]
@maveonair, could you please also add a helix package for Ubuntu 20.04 to your PPA?

**Comment by xsbee** [comment]
A Debian package would also be highly solicited.

**Comment by David-Else** [comment]
@maveonair I have added your repository to the official documentation that I am currently rewriting / refactoring. 

Please can you confirm this info is correct:

- Your repo works for Ubuntu / PopOS? Which versions?
- Any other OS's it works on, and any specific versions of the OS's?
 
Thanks, I don't know any Debian distro terminology :)

## Installing Helix on Linux via Third-Party Repositories

If Helix is not available through your distribution's official repository, you
may need to use a third-party repository.

### Ubuntu/Pop!\_OS PPA Repository

Helix is available via [Fabian Mettler's PPA](https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor):

```sh
sudo add-apt-repository ppa:maveonair/helix-editor
sudo apt update
```

**Comment by maveonair** [comment]
> @maveonair I have added your repository to the official documentation that I am currently rewriting / refactoring.
> 
> Please can you confirm this info is correct:
> 
> * Your repo works for Ubuntu / PopOS? Which versions?
> * Any other OS's it works on, and any specific versions of the OS's?
> 
> Thanks, I don't know any Debian distro terminology :)
> 

Currently I have published only for Ubuntu 22.04 (codename Jammy).

> ## Installing Helix on Linux via Third-Party Repositories
> If Helix is not available through your distribution's official repository, you may need to use a third-party repository.
> 
> ### Ubuntu/Pop!_OS PPA Repository
> Helix is available via [maveonair's PPA](https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor):
> 
> ```shell
> sudo add-apt-repository ppa:maveonair/helix-editor
> sudo apt update
> ```

Would it be ok for you to use my "internet" name instead?

**Comment by David-Else** [comment]
@maveonair Cheers! I have changed it to the below. If you publish for other versions or distributions please could you ping me to update the docs.

### Ubuntu 22.04 PPA Repository

Helix is available via [Maveonair's PPA](https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor):

```sh
sudo add-apt-repository ppa:maveonair/helix-editor
sudo apt update
```

**Comment by maveonair** [comment]
> @maveonair Cheers! I have changed it to the below. If you publish for other versions or distributions please could you ping me to update the docs.

Sorry, I forgot to tell you that the actual installation command above is missing:

 ### Ubuntu 22.04 PPA Repository
 
 Helix is available via [Maveonair's PPA](https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor):
 
 ```shell
 sudo add-apt-repository ppa:maveonair/helix-editor
 sudo apt update
 sudo apt install helix
 ```

**Comment by maveonair** [comment]
> @maveonair, could you please also add a helix package for Ubuntu 20.04 to your PPA?

@kirillmorozov @David-Else Helix is now also available for Ubuntu 20.04 (Codename focal) 😊:

![Screenshot from 2023-01-14 09-33-20](https://user-images.githubusercontent.com/426412/212463756-b46482e6-199d-46ba-87a3-33c7c9d193ac.png)

**Comment by David-Else** [comment]
### Ubuntu 20.04 LTS (Focal Fossa) / 22.04 Ubuntu 22.04 LTS (Jammy Jellyfish) PPA Repository

Helix is available via [Maveonair's PPA](https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor):

```sh
sudo add-apt-repository ppa:maveonair/helix-editor
sudo apt update
sudo apt install helix
```

**Comment by maveonair** [comment]
> ### Ubuntu PPA Repository for  20.04 LTS (Focal Fossa) and 22.04 LTS (Jammy Jellyfish) 
> 
> Helix is available via [Maveonair's PPA](https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor):
> 
> ```shell
> sudo add-apt-repository ppa:maveonair/helix-editor
> sudo apt update
> sudo apt install helix
> ```

What do you think about this instead?

**Comment by David-Else** [comment]
I just committed hopefully the final revision of the installation section, it ended up as this format, when you see the entire document I think you will love it :) :

## Installing Helix on Linux via Third-Party Repositories

If Helix is not available through your distribution's official repository, use a
third-party repository.

- Ubuntu

Helix is available for 20.04 LTS (Focal Fossa) and 22.04 Ubuntu 22.04 LTS (Jammy
Jellyfish) via [Maveonair's PPA](https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor):

```sh
sudo add-apt-repository ppa:maveonair/helix-editor
sudo apt update
sudo apt install helix
```

- Fedora/RHEL Linux

Helix is available via `copr`:

```sh
sudo dnf copr enable varlad/helix
sudo dnf install helix
```

...

**Comment by David-Else** [comment]
@maveonair I could leave out the link to your repo and just say `PPA`  like the Fedora one, I only linked as I thought there might be more info for people trying to make it work on Ubuntu based distros, what do you think?

**Comment by StefanUlbrich** [comment]
@maveonair , Thanks for the package! Could you create a package for 22.10 too please?

**Comment by xsbee** [comment]
I don't know why is this issue is closed. It's a perfectly valid and active issue. It is prejudicial, in my opinion.

**Comment by xsbee** [comment]
```
Hit:1 http://in.archive.ubuntu.com/ubuntu kinetic InRelease
Hit:2 http://security.ubuntu.com/ubuntu kinetic-security InRelease               
Hit:3 http://in.archive.ubuntu.com/ubuntu kinetic-updates InRelease              
Ign:4 https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu kinetic InRelease
Hit:5 http://in.archive.ubuntu.com/ubuntu kinetic-backports InRelease             
Err:6 https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu kinetic Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done                              
E: The repository 'https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details
```

**Comment by David-Else** [comment]
@xsbee I am afraid I have no idea about the messages, I think you meant to ping maveonair who created the repository.

**Comment by xsbee** [comment]
> @xsbee I am afraid I have no idea about the messages, I think you meant to ping maveonair who created the repository.

@David-Else I see. It is that the PPA isn't working. @maveonair Can you please fix for jellyfish?

**Comment by David-Else** [comment]
> I don't know why is this issue is closed. It's a perfectly valid and active issue. It is prejudicial, in my opinion.

@xsbee I think it is closed because there now is a package for Ubuntu.

**Comment by maveonair** [comment]
@xsbee @David-Else @StefanUlbrich 
There is no package for Ubuntu 22.10 in PPA yet, only for the two latest LTS releases. This is the reason why @xsbee cannot install the package on his computer.

I will look into it to also provide a version for 22.10.

**Comment by maveonair** [comment]
> > @xsbee I am afraid I have no idea about the messages, I think you meant to ping maveonair who created the repository.
> 
> @David-Else I see. It is that the PPA isn't working. @maveonair Can you please fix for jellyfish?

Jellyfish is 22.04 and the PPA is providing the package for it, which I am using is right now on my machines.

**Comment by maveonair** [comment]
@xsbee I have published a package to the PPA for the latest Ubuntu version 22.10 Kinetic Kudu. 

@everyone If you use my PPA and have any problems or suggestions, please create an issue here from now on: https://github.com/maveonair/helix-ppa/issues.

**Comment by xsbee** [comment]
> @xsbee I have published a package to the PPA for the latest Ubuntu version 22.10 Kinetic Kudu.
> 
> @everyone If you use my PPA and have any problems or suggestions, please create an issue here from now on: https://github.com/maveonair/helix-ppa/issues.

@maveonair Thank you for support!

**Comment by David-Else** [comment]
I have updated the docs accordingly: https://github.com/helix-editor/helix/pull/5534/commits/a6894a1ba7d57e9265374d552ae9b2ebf3251fb0

**Comment by febriliankr** [comment]
I still get errors trying to install helix on Ubuntu 22.10, `E: Unable to locate package helix`
```
root@febrilianx:~# sudo add-apt-repository ppa:maveonair/helix-editor
Repository: 'deb https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu/ kinetic main'
Description:
A post-modern text editor.

The source code used to build the package can be found here: https://github.com/maveonair/helix-ppa.
More info: https://launchpad.net/~maveonair/+archive/ubuntu/helix-editor
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/maveonair-ubuntu-helix-editor-kinetic.list
Adding deb entry to /etc/apt/sources.list.d/maveonair-ubuntu-helix-editor-kinetic.list
Found existing deb-src entry in /etc/apt/sources.list.d/maveonair-ubuntu-helix-editor-kinetic.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/maveonair-ubuntu-helix-editor-kinetic.list
Adding key to /etc/apt/trusted.gpg.d/maveonair-ubuntu-helix-editor.gpg with fingerprint 27642B9FD7F1A161FC2524E3355A4FA515D7C855
Hit:1 https://download.docker.com/linux/ubuntu kinetic InRelease
Hit:2 http://security.ubuntu.com/ubuntu kinetic-security InRelease
Get:3 http://mirrors.digitalocean.com/ubuntu kinetic InRelease [267 kB]
Hit:4 http://mirrors.digitalocean.com/ubuntu kinetic-updates InRelease
Hit:5 http://mirrors.digitalocean.com/ubuntu kinetic-backports InRelease
Hit:6 https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu kinetic InRelease
Hit:7 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Fetched 267 kB in 2s (122 kB/s)
Reading package lists... Done
root@febrilianx:~# sudo apt install helix
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package helix
root@febrilianx:~# sudo apt update
Hit:1 https://download.docker.com/linux/ubuntu kinetic InRelease
Get:2 http://mirrors.digitalocean.com/ubuntu kinetic InRelease [267 kB]
Hit:3 http://mirrors.digitalocean.com/ubuntu kinetic-updates InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu kinetic-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu kinetic-security InRelease
Hit:6 https://ppa.launchpadcontent.net/maveonair/helix-editor/ubuntu kinetic InRelease
Hit:7 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Fetched 267 kB in 1s (258 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
132 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@febrilianx:~# sudo apt install helix
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package helix
```

**Comment by maveonair** [comment]
I dropped support for 22.10. Only provide packages for:

- 20.04 (Long Term Support)
- 22.04 (Long Term Support)
- 23.04 

Any chance that you upgrade to 23.04?

**Comment by xsbee** [comment]
Any plans for a Debian package?

**Comment by maveonair** [comment]
No, it’s already enough work to provide the Ubuntu packages. But feel free to use the scripts in this repository to build your own package on Debian.

**Comment by David-Else** [comment]
> Any plans for a Debian package?

Debian 12 would be a good one to support, it looks really good :)

**Comment by maveonair** [comment]
> > Any plans for a Debian package?
> 
> Debian 12 would be a good one to support, it looks really good :)

Unfortunately it would not be possible to build the package on Debian 12 as it only offers rustc 1.63.0, and version 1.64.0 or higher is needed to build Helix at this moment :/. Ubuntu offers rustc 1.65.0, which is why it works there.
