### ISSUE TITLE
Panic when trying to open files in $HOME

### ISSUE THREAD

**Issue by cjohansson** [helix-editor/helix#81]
Present-working-directory of shell is located at `$HOME/Downloads/helix-editor/helix`

1. `$ RUST_BACKTRACE=1 hx`
2. `:open ../../` (Panic occurs when second slash is typed)

thread 'main' panicked at 'index out of bounds: the len is 10070 but the index is 61356', helix-tui/src/buffer.rs:185:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:69:5
   3: helix_tui::buffer::Buffer::clear_with
   4: <hx::ui::prompt::Prompt as hx::compositor::Component>::render
   5: hx::compositor::Compositor::render
   6: hx::main::{{closure}}
   7: tokio::runtime::enter::Enter::block_on
   8: tokio::runtime::Runtime::block_on
   9: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Ubuntu 20.04.2 LTS

**Comment by archseer** [comment]
I think this should be fixed on master by now. Let me know to reopen if necessary.

**Comment by cjohansson** [comment]
The issue remains, tested on commit `b873fb9897bb5b24a60cca3d9fa69285446a857f`

**Comment by archseer** [comment]
What terminal emulator are you using?

**Comment by cjohansson** [comment]
zsh

```
$ basename "/"$(ps -f -p $(cat /proc/$(echo $$)/stat | cut -d \  -f 4) | tail -1 | sed 's/^.* //')
gnome-terminal-server
```
```
$ echo $TERM
xterm-256color
```
But I get the exact same issue in bash, see below (or am I doing something wrong here?)

```
$ bash        
$ cd ~/Downloads/helix-editor/helix/
$ RUST_BACKTRACE=1 hx
thread 'main' panicked at 'index out of bounds: the len is 1920 but the index is 49296', helix-tui/src/buffer.rs:185:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:69:5
   3: helix_tui::buffer::Buffer::clear_with
   4: helix_term::ui::prompt::Prompt::render_prompt
   5: helix_term::compositor::Compositor::render
   6: helix_term::application::Application::handle_terminal_events
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: tokio::park::thread::CachedParkThread::block_on
   9: tokio::runtime::thread_pool::ThreadPool::block_on
  10: tokio::runtime::Runtime::block_on
  11: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by archseer** [comment]
Terminal as in alacritty, kitty, GNOME terminal.

I was able to replicate the bug, it seems to happen on a large folder where there's too many completions. Looking at a quick fix now

**Comment by archseer** [comment]
Pushed a fix in https://github.com/helix-editor/helix/commit/83723957fe8a1f4b87b4590fc64dce941e162637

**Comment by cjohansson** [comment]
Thanks, I can confirm it is working now

**Comment by archseer** [comment]
Thanks for reporting it!
